name: moduled_intl_utils
description: moduled_intl_utils is a dart library that generates Dart localization code from ARB file for multiple modules. Generated code relies on Intl library. Forked from https://github.com/localizely/intl_utils
version: 2.7.0
homepage: https://github.com/localizely/moduled_intl_utils

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=3.19.5"

dependencies:
  analyzer: ^6.4.1
  archive: ^3.4.10
  args: ^2.5.0
  dart_style: ^2.3.6
  http: ^1.2.1
  intl: ^0.19.0
  path: ^1.9.0
  petitparser: ^6.0.2
  yaml: ^3.1.2
  intl_utils: ^2.8.7

dev_dependencies:
  build_runner: ^2.4.9
  lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.25.3
